[workspace]

members = [
    "rustboy-gb",
    "rustboy-wasm",
    "rustboy-gui",
]
#lto = true

[profile.release.package.rustboy-gb]
#lto="fat"
#codegen-units = 1
#panic = "abort"
overflow-checks = true
