[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"
modular-bitfield = "0.11.2"
sdl2 = {version="0.35.2", features=["gfx"]}
anyhow = "1.0"

[profile.release]
lto="fat"
codegen-units = 1
panic = "abort"
debug= true
overflow-checks = true

[lib]
name = "rustboy"
path = "src/lib.rs"
