[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rand = "0.8.4"
raylib = {version = "3.7"}
sdl2 = "0.35.2"
text_io = "0.1.9"
modular-bitfield = "0.11.2"
